name: flix_pedia
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  animations: ^2.0.8
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  fluid_bottom_nav_bar: ^1.4.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.1
  firebase_database: ^10.3.4
  google_sign_in: ^6.1.5
  get: ^4.6.6
  fluttertoast: ^8.2.2
  motion_toast: ^2.7.9
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  liquid_progress_indicator_v2: ^0.5.0
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.0
  youtube_player_flutter: ^8.1.2
  comment_tree: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/