final List<String> movieFacts = [
  "First movie ever made: ",
  "'Roundhay Garden Scene' (1888).",
  'Longest film: "Logistics" (2012),',
  '35 days.',
  '"Gone with the Wind" (1939): ',
  '1st color film to win Best Picture.',
  'First animated feature: ',
  '"Snow White" (1937) by Disney.',
  '"Avatar" (2009): Highest-grossing movie, ',
  'surpassing "Endgame" (2019).',
  '"The Return of the King" (2003): ',
  '11 Oscars.',
  'First recorded kiss in film: 1896, ',
  '"The May Irwin Kiss."',
  'Shortest Oscar winner: ',
  '"Fresh Guacamole" (2012), 1m 40s.',
  'Original "Jurassic Park" (1993) title: ',
  '"Eath" and "Ancient Future."',
  '"Psycho" (1960): ',
  '1st US film to show a flushing toilet.',
  '"The Exorcist" (1973): ',
  'Used a pig squeal for demon sounds.',
  '"Casablanca" (1942): ',
  'Filmed on Hollywood soundstage due to WWII.',
  '"Rocky" series: ',
  'Sylvester Stallone nominated ',
  'for acting and writing.',
  '"The Matrix" (1999): ',
  'Popularized "bullet time" filmmaking.',
  '"The Dark Knight" (2008): ',
  '1st superhero film to gross \$1 billion.',
  '"E.T." (1982): ',
  'Originally featured aliens from Brodo Asogi.',
  '"Die Hard" (1988): ',
  'Based on Roderick Thorp\'s ',
  '"Nothing Lasts Forever."',
  '"Rope" (1948): Filmed in 10 takes, ',
  'each 10 minutes long.',
  'First movie theater: ',
  'Opened in Paris in 1895.',
  '"Shawshank Redemption" (1994): ',
  'Cult classic on home video.',
  '"Silence of the Lambs" (1991): ',
  'Only horror film to win Best Picture.',
  '"Pulp Fiction" (1994): ',
  'Known for non-linear narrative and profanity.',
  '"The Dictator" (2012): ',
  'Most takes in a scene, 99 takes.',
];
